# Generated by Django 4.2.20 on 2025-03-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appendices', '0009_appendix_delete_appendixpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appendix',
            options={'ordering': ['name'], 'verbose_name': 'appendix', 'verbose_name_plural': 'appendices'},
        ),
    ]
